### PR TITLE
feat: Profile View

### PR DESCRIPTION
**Pull request by 10dimensions**
- Profile Badge
- Disconnect Wallet
- Metadata details
- Withdraw proceeds

### CODE REVIEW

**Review by gravenp — CHANGES_REQUESTED** [review]
Thanks, @10dimensions. I know you said this was still a work in progress, so you might already be aware, but here's the punchlist from my testing as-is:

-The border of the Wallet Balance/Address element is inconsistent (see 1st screenshot)
-When hovering over the Wallet Balance/Address element, it doesn't indicate that it is clickable (no hover transition to hand pointer)
-Text on the "Disconnect" wallet button isn't showing (see 2nd screenshot)
-The Unclaimed Transfer Proceeds value is missing a decimal/conversion from wei (2nd screenshot)
-The styling of the X button on the profile modal is off and doesn't have the right hover state or click area (2nd screenshot)
-Hover and click area on the Claim Proceeds button aren't right. Can't click on the button if hovered over any text. Can click on the button outside of the text.
-Claim Proceeds button doesn't trigger a transaction yet

Screen Shot 2021-09-06 at 4 00 22 PM

Screen Shot 2021-09-06 at 4 00 58 PM

**Comment by 10dimensions** [comment]
Noted! The Mouse hover functionality can be overridden.
I'm guessing the flexbox of the parent component was conflicting.

Will make a patch commit on this by tomorrow

**Comment by 10dimensions** [comment]
Issues corrected

Cursor pointer
Disconnect text
Eth decimal place corrections
Withdraw proceeds debugging (if this works that'd be great)

**Comment by codynhat** [comment]
Closing this as withdrawals are no longer needed.

**Comment by codynhat** [comment]
Going to reopen this for the profile view. It should still give @10dimensions some cred once merged.

**Pull request merged**
