### PR TITLE
fix: flag new parcel to update fields on claim

### LINKED ISSUE #270: Panel issues after claiming a parcel
**Describe the bug**
Related to https://github.com/Geo-Web-Project/cadastre/pull/267

When new parcels are claimed, I am intermittently getting a panel with stuck spinners and an incorrect button displayed:

1) Ceramic content doesn't load
2) `For Sale Price` and `Licensee` don't load
3) _Place Bid_ button is shown
4) `Parcel ID` DOES load

Expected: Content and data should eventually all load and only then should the _Edit Parcel_ and _Edit Media Gallery_ buttons show.

Leaving the panel open for long periods of time does not resolve the issue. Closing the panel and navigating away from the parcel and back doesn't seem to work either. Refreshing the page and navigating back does.

### PR DESCRIPTION
**Pull request by tnrdd**
# Description

When a new parcel is claimed refetch until the data is returned from the subgraph query.

# Issue

fixes #270 
# Checklist:

- [x] My commit message follows the Conventional Commits specification
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my code
- [x] My changes generate no new warnings
- [x] My PR is rebased off the most recent `develop` branch
- [x] My PR is opened against the `develop` branch

# Alert Reviewers

@codynhat @gravenp

### CODE REVIEW

**Review by gravenp — COMMENTED** [review]
Thanks for jumping right on this @tnrdd! I tested several times and got the results we wanted with panel data. One loaded immediately & others showed the spinners for a bit (without any buttons) which then resolved in a short time.

The parcel shape on the map was disappearing without coming back though. Should the fix implemented in https://github.com/Geo-Web-Project/cadastre/pull/219 still apply?

**Comment by tnrdd** [comment]
> The parcel shape on the map was disappearing without coming back though. Should the fix implemented in #219 still apply?
> 
Yes it should because the logic for the parcel shape on the map was not touched.

**Comment by gravenp** [comment]
> Yes it should because the logic for the parcel shape on the map was not touched.

Ok. I'll keep an eye on the parcels loading and we can approve/merge this change (especially because we're looking at other parcel shape+subgraph stuff).

Nice work!

**Review by gravenp — APPROVED** [review]
@codynhat ready for your review.

**Comment by tnrdd** [comment]
It might be some issue with the preview deployment because I just double checked and my local build works as expected.
Can we try to retrigger the workflow?

**Comment by gravenp** [comment]
> It might be some issue with the preview deployment because I just double checked and my local build works as expected. Can we try to retrigger the workflow?

The parcel is still dropping on the rebuild. 

I confirmed that the parcel is persisting on the `main` build. When we push this change live, I'll check it out to confirm its an environment thing.

**Comment by tnrdd** [comment]
I was able to reproduce it in `main` a few times too, so it's not a problem of the preview.

**Comment by gravenp** [comment]
> I was able to reproduce it in `main` a few times too, so it's not a problem of the preview.

Bummer. More intermittent stuff 😔. Do you have a beat on how you might address it in this PR or want to proceed with merging this as-is and raise a new ticket and PR?

**Comment by tnrdd** [comment]
> Bummer. More intermittent stuff 😔. Do you have a beat on how you might address it in this PR or want to proceed with merging this as-is and raise a new ticket and PR?
>
Unfortunately I don't yet understand why it happens so can't fix it here, it seems like there is some place in the map where it always works and  other places where it doesn't but need to investigate more.

**Comment by gravenp** [comment]
> Unfortunately I don't yet understand why it happens so can't fix it here, it seems like there is some place in the map where it always works and other places where it doesn't but need to investigate more.

Sounds good. We'll keep an eye on it with https://github.com/Geo-Web-Project/cadastre/issues/268 too. 

Thanks again for knocking out the panel part. Nice work.

**Review by codynhat — APPROVED** [review]

**Pull request merged**
