### PR TITLE
Feature/torus wallet

### PR DESCRIPTION
**Pull request by 10dimensions**
Multi Wallet Implementation using web3-react
1) injected-connector
2) walletconnect-connector
3) fortmatic-connector
4) portis-connector
5) torus-connector

Designed a simple bootstrap UI to display wallet options

### CODE REVIEW

**Comment by codynhat** [comment]
This is blocked by #65

**Review by codynhat — APPROVED** [review]

**Comment by gravenp** [comment]
@10dimensions This has a few outstanding items to be addressed before going to production.

**Styling**
-Wallet icons should middle aligned on the right side of the buttons in the panel
-Replace all icons with .svg versions (shared Drive folder; let me know if these still render blurry)
-Wallet names should be left justified on the buttons (with spacing for the "Connection Status" dot on the far left) 
-Remove the silver border/drop-shadow around the buttons
-Rename "Injected" to "Metamask" (temporary until we can recognize the injected provider)

*Functionality*
-When a user successfully connects their wallet on the Kovan network, close the panel.
-When a user connects a wallet to any network other than Kovan, change the "Connect Wallet" button to the "Wrong Network" button. Display the red "Connection Status" dot to the left of the wallet name.

**Comment by 10dimensions** [comment]
@gravenp 
W.r.t to logo placement, the right corner has a small spinner to indicate connectivity and actions.

That's why I brought it to left. Logo at left, name center and spinner to the right.

Secondly, pngs are suitable for react as opposed to svg . I think one of the wallets (wallet connect) has a blurry logo officially :)

**Comment by gravenp** [comment]
Thanks @10dimensions!

Added right-sized PNGs to the same logo folder. 

As for the button element alignment, let's have the logos are center-aligned relative to each other on the left and the wallet names a fixed distance to the right the logos (left-aligned relative to each other).

Screen Shot 2021-07-30 at 11 34 43 AM

Screen Shot 2021-07-30 at 11 34 26 AM

**Comment by gravenp** [comment]
@10dimensions Doesn't look like your last commit to remove the border took and some of these other issues are still there:

-Border/3D outline is showing on the wallet buttons. Buttons should be flat
-Need to rename "Injected" to "Metamask"
-Panel should automatically close after successful connection to wallet on Kovan
-Instead of a green checkmark when connected to the wrong network, should show a red dot (or other red square icon if you prefer)


> @10dimensions This has a few outstanding items to be addressed before going to production.
> 
> **Styling**
> -Wallet icons should middle aligned on the right side of the buttons in the panel
> -Replace all icons with .svg versions (shared Drive folder; let me know if these still render blurry)
> -Wallet names should be left justified on the buttons (with spacing for the "Connection Status" dot on the far left)
> -Remove the silver border/drop-shadow around the buttons
> -Rename "Injected" to "Metamask" (temporary until we can recognize the injected provider)
> 
> _Functionality_
> -When a user successfully connects their wallet on the Kovan network, close the panel.
> -When a user connects a wallet to any network other than Kovan, change the "Connect Wallet" button to the "Wrong Network" button. Display the red "Connection Status" dot to the left of the wallet name.

**Comment by 10dimensions** [comment]
All 4 issues sorted. Rebuilding again.
- Red dot
- Border none
- Rename to Metamask
- Auto-close menu on kovan connect

**Comment by gravenp** [comment]
Chatted with Vishal on this. All looks good visually and base scenario works as intended. Few kinks to work out with wallet disconnection and changing networks that he's looking into now.

**Pull request merged**
