### PR TITLE
feat: OutstandingBidView handles modified flows

### LINKED ISSUE #242: Update the `OutstandingBidView` card to address parcels with outstanding bids that have had their streams modified
**Description**
It is possible for a parcel licensor to manually update (cancel, decrease, or increase) their `Network Fee` payment stream when they have an outstanding bid. As part of https://github.com/Geo-Web-Project/core-contracts/pull/92, any such modification will result in the ending datetime of the response period being pulled forward to the time of the action.

To provide additional user context for these scenarios, the following changes should be made to the [OutsandingBidView card](https://github.com/Geo-Web-Project/cadastre/blob/main/components/cards/OutstandingBidView.tsx).

**Requirements**
- When a parcel with an outstanding bid has its `Network Fee` stream modified, it will be handled as if the bid response window has passed/been pulled forward, and the `Trigger Transfer` button and corresponding fields should be shown for ALL users.
- Add warning text (in red) above the bid/transaction details that reads as follows:
  - "The network fee stream for this parcel was modified while there was an outstanding bid, so the bid response window is closed. The previous licensor will receive their original For Sale Price net their network fee payment shortfall or surplus upon transfer." 
- Add a `Transfer Payout` field under the `For Sale Price (Bid)` field that displays the previous licensor's live calculated net payout:
  - The value should = the previous `For Sale Price` plus or minus the network fee surplus (flow increase) or shortfall (flow decrease & cancellation) since the stream modificiation occured.
- Change the final field name from `Deadline` to `Action Date:`
  - The value for this field should equal the datetime that the stream was modified and the bid response window was pulled forward to

### PR DESCRIPTION
**Pull request by codynhat**
## Description

fixes #242 

## Checklist:

- [x] My commit message follows the Conventional Commits specificaiton
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My PR is rebased off the most recent `develop` branch
- [x] My PR is opened against the `develop` branch

## Alert Reviewers

@gravenp

### CODE REVIEW

**Comment by codynhat** [comment]
@gravenp I believe the incorrect payout amount is now fixed. Let me know if you can still reproduce.

**Comment by gravenp** [comment]
> @gravenp I believe the incorrect payout amount is now fixed. Let me know if you can still reproduce.

Payments look right in tests tonight. I'm going to let a few more exotic scenarios run for a while and check them tomorrow before calling this good if that's alright with you.

One new issue I came across: `Action Date` is showing the UTC time but with the machine/local timezone tag.

**Comment by gravenp** [comment]
I'm also seeing parcel names and content links not process/save correctly:

**Comment by gravenp** [comment]
I'm now seeing parcel names & content links not save properly too: 

Uncaught (in promise) Error: HTTP request to 'https://g12-a-ceramic.3boxlabs.com/api/v0/streams' failed with status 'Internal Server Error': {"error":"Can not verify signature for commit bagcqceramasm3jcezsphyuv4scp4lwsdiavcqqjfk6vatyu3ixvgfwxa7zva: Signature does not belong to issuer"}

**Comment by codynhat** [comment]
> > @gravenp I believe the incorrect payout amount is now fixed. Let me know if you can still reproduce.
> 
> Payments look right in tests tonight. I'm going to let a few more exotic scenarios run for a while and check them tomorrow before calling this good if that's alright with you.
> 
> One new issue I came across: `Action Date` is showing the UTC time but with the machine/local timezone tag.

Action date should be fixed on latest commit.

**Review by gravenp — APPROVED** [review]
The latest commit looks great, @codynhat! Good to go! Nice work.

**Pull request merged**
