### PR TITLE
feat: Integrate ACL + Diamonds Architecture

### LINKED ISSUE #231: Add ETHx Approval Flow to the Cadastre
**Description**
The Geo Web's v3 core contracts implemented in https://github.com/Geo-Web-Project/core-contracts/pull/75 utilize an [EIP2535 Diamonds Proxy](https://eips.ethereum.org/EIPS/eip-2535) & [Superfluid ACL](https://docs.superfluid.finance/superfluid/developers/interactive-tutorials/acl-features) architecture. This new architecture requires explicit ETHx token approval transactions for Fair Launch Claims and Bid Placement (i.e. the lump sum payments) in addition to the transaction to start the corresponding Network Fee stream. 

This ticket will add the UI elements and approval flow for these scenarios.

**Business Requirements**
- Change the `Wrap to ETHx` button color to purple
- Stack the `Wrap to ETHx` button & the appropriate "transaction trigger" button 
  - Extend their width to the full panel (make it consistent with the "Edit" buttons a user sees when opening a parcel)
- If the connected wallet doesn't have a large enough ETHx allowance **for the selected parcel** to complete the required transfer (i.e. stream buffer, one-time claim fee, or bid collateral) and/or start the corresponding stream, then the "transaction trigger" button should be used to trigger Transfer and/or Stream allowance transactions under the following conditions:
  - If only the ERC20 allowance is insufficient to cover the required one-time payments, display `Allow ETHx Transfer` & trigger a transaction for an unlimited allowance with the button.
  - If only the [flow allowance](https://docs.superfluid.finance/superfluid/developers/solidity-examples/cfa-access-control-list-acl) is insufficient to cover the required increase in stream value, display `Allow ETHx Stream` & trigger a transaction for an unlimited flow allowance 
  - If both the transfer & flow allowances are insufficient display `Allow ETHx Transfer + Stream` & trigger transactions for both an unlimited transfer and flow allowance
- Show a spinner and progress counter ({# txs Confirmed}/{# txs required}) on the button while the allowance transactions are pending  [Screen 2]
  - Display help text below the button that reads "Confirm the required allowance transaction(s) in your wallet to proceed." 
- Once the required allowance transactions are confirmed, show the appropriate/existing transaction button used to complete the land transaction [Screen 3]

**Wireframes**
Screen 1
Approval Flow - Step 1

Screen 2
Approval Flow - Step 2

Screen 3
Approval Flow - Step  3

### PR DESCRIPTION
**Pull request by codynhat**
# Pull Request Template

## Description

Please include the type of fix and description of your change according to the (Conventional Commits specification)[https://www.conventionalcommits.org/en/v1.0.0/]. 

Closes #231, #226

## Checklist:

- [x] My commit message follows the Conventional Commits specificaiton
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My PR is rebased off the most recent `develop` branch
- [x] My PR is opened against the `develop` branch

## Alert Reviewers

@codynhat @gravenp

### CODE REVIEW

**Comment by codynhat** [comment]
This is ready to review except for reclaiming.

Closes #231

**Comment by gravenp** [comment]
@codynhat The transaction panel doesn't appear to be updating after the confirmation of the second "allow" transaction is confirmed. Waited approximately 2 minutes and still saw the "1/2 Spinner" showing.

The first allow confirmation updated fine. User can work around the issue by closing the panel and reopening.

**Comment by gravenp** [comment]
I am also unable to lower the For Sale Price of my parcels. Transactions revert with the following error:

Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x2aF85396137cd725d38053f8cF5eAe939479a9F4","to":"0x267304a91a58A51f402cB080f4BB73F0a65DC762","data":"0xf11663e80000000000000000000000000000000000000000000000000000000036cfbcdf00000000000000000000000000000000000000000000000004064976a8dd0000","accessList":null}, error={"code":-32603,"message":"execution reverted","data":{"originalError":{"code":3,"data":"0x4e487b710000000000000000000000000000000000000000000000000000000000000011","message":"execution reverted"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.8)

**Comment by codynhat** [comment]
> I am also unable to lower the For Sale Price of my parcels. Transactions revert with the following error:
> 
> Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x2aF85396137cd725d38053f8cF5eAe939479a9F4","to":"0x267304a91a58A51f402cB080f4BB73F0a65DC762","data":"0xf11663e80000000000000000000000000000000000000000000000000000000036cfbcdf00000000000000000000000000000000000000000000000004064976a8dd0000","accessList":null}, error={"code":-32603,"message":"execution reverted","data":{"originalError":{"code":3,"data":"0x4e487b710000000000000000000000000000000000000000000000000000000000000011","message":"execution reverted"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.8)

Ok thanks. I was able to reproduce this.

**Comment by codynhat** [comment]
@gravenp Decreasing your for sale price should be working now.

**Comment by gravenp** [comment]
> @gravenp Decreasing your for sale price should be working now.

Yup! Looks good now.

**Comment by gravenp** [comment]
Accepting a bid results in the Cadastre crashing (black screen showing with a client-side exception message). From the console:

- TypeError: M.geoWebParcel.pendingBid is null
- A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

[console-export-2022-9-1_16-48-17.txt](https://github.com/Geo-Web-Project/cadastre/files/9473809/console-export-2022-9-1_16-48-17.txt)

**Comment by codynhat** [comment]
@gravenp Alright, the outstanding issues you've mentioned should all be fixed:

- [x] Not completing second action
- [x] Crash on accept bid
- [x] Hardcoded buffer amounts

**Comment by gravenp** [comment]
Tests on rejecting bids (and setting a higher price) look good. Nice work, @codynhat!

**Pull request merged**
