### PR TITLE
feat: show globe view on map load

### LINKED ISSUE #347: Default the mainnet Cadastre to whole Earth view
Instead of zooming in on NYC, load the Cadastre map with a view of the whole Earth.

Testnet can remain as-is to concentrate claims and see a critical mass of activity.

### PR DESCRIPTION
**Pull request by tnrdd**
# Description

Show a view of the whole earth on map load.

# Issue

fixes #347 

# Checklist:

- [x] My commit message follows the Conventional Commits specification
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my code
- [x] My changes generate no new warnings
- [x] My PR is rebased off the most recent `develop` branch
- [x] My PR is opened against the `develop` branch

# Additional comments
- Set `interactiveLayerIds` after the map loads and the grid is calculated.

# Alert Reviewers

@codynhat @gravenp

### CODE REVIEW

**Comment by codynhat** [comment]
Do we want the globe to also be on the testnet?

**Comment by tnrdd** [comment]
Maybe it's better to leave it zoomed in on testnet for easier testing. What do you think?

**Comment by gravenp** [comment]
Yeah, if we can keep testnet claims focused in NYC by using an env variable that would be perfect.

**Review by gravenp — APPROVED** [review]
Staging and Test look good on my end. Thanks @tnrdd.

It looks like this also includes the cleanup of the `interactiveLayerIDs`.

@codynhat , ready for you.

**Pull request merged**
