### PR TITLE
Add Map Search functionality

### PR DESCRIPTION
**Pull request by 10dimensions**
- Implement Geocoded search
- Embed inside React-Map-GL Component, with search bar separated

To Do:
- useCallback to manage events
- Potential Styling if needed

### CODE REVIEW

**Review by gravenp — CHANGES_REQUESTED** [review]
Nice! This makes navigation sooo much better.

Here are the open items that I see (including those you pointed out in chat):
- After hitting enter, the drop-down doesn't close automatically (and clicking outside the input box starts parcel selection)
- Sometimes, target of the search bar does not work initially (input typing)
- Remove the dotted external border around the search bar that's activated when in focus
- Right justify the search bar. The left side of the screen has our parcel details panel go in and out, the center interferes with the map in some cases, so right side of the screen it is.

**Comment by gravenp** [comment]
@10dimensions  thanks for making these updates.

Fixed:
- Interaction with search bar works is smooth
- Search results go away after search entry

Needs attention:
- I should have been more specific with the placement of the search bar on the right of the page... My bad! Let's have it be center aligned with the "wallet profile element" on the right (this is the disconnect/address right now, but will change soon so let's account for that).
- The dotted lines are still showing around the search bar. Not a huge deal, but if that's easy to remove, I'd prefer it.

**Comment by 10dimensions** [comment]
@gravenp Can you give a visual cue as to the placement & also the border issue ?
Probably my resolution is smaller, and hence looks alright...

**Comment by gravenp** [comment]
Current Search Bar Location
New Search Bar Location

We just need a bit of spacing between the right side of the search bar and the edge of the page. See screenshots. Middle aligning with the header wallet element seems like a good place (depicted with red dotted line). If the bar needs to be shorted to create more spacing on the right, go ahead and do that.

**Review by gravenp — APPROVED** [review]
Looks good now. Thanks!

**Pull request merged**
