### PR TITLE
Set the max claim payment to equal the required auction bid during fair launch

### LINKED ISSUE #152: The max claim payment should equal the required auction bid at submission
In the fair launch claim module, the value shown in the `Max Claim Payment (to Treasury):` field and authorized in the corresponding transaction should be set equal to the Dutch auction’s current required bid (with the actual payment made still always being less than this value due to passage of time between transaction signing and inclusion in a block).

\
It is currently being displayed/set to the claimer’s `For Sale Price`.  

[Read more about this task and rewards on Dework.xyz](https://app.dework.xyz/geo-web/cadastre?taskId=4e897383-651c-4e40-a2ce-76e6009573ee)

### PR DESCRIPTION
**Pull request by tnrdd**
Closes #152 

The current required bid in the `FairLaunchInfo` and  `TransactionSummaryView` cards are updated every second with the remaining time.

### CODE REVIEW

**Comment by gravenp** [comment]
@codynhat, in order for me to test this one in dev, I think we'll need to update the fair launch auction start time to ~now. If we want to hold off on that, I'd be OK if you validate the code and/or test locally. Lmk.

**Comment by codynhat** [comment]
@gravenp The fair launch auction should be started now.

**Review by gravenp — COMMENTED** [review]
Looks good on my end. Thanks, @tnrdd!

@codynhat you can approve & merge if you agree.

**Review by codynhat — APPROVED** [review]
LGTM

**Pull request merged**
