### PR TITLE
feat: metadata update

### LINKED ISSUE #463: Utilize standard NFT metadata for parcel name & URI
**Description**
In conjunction with the move to a MUD-based content layer (https://github.com/Geo-Web-Project/cadastre/issues/462), we're eliminating the Basic Profile schema. Instead, we can use the parcel license NFT & standard metadata instead (`name` & `external_link`).

**Requirements**
- Update the Edit Parcel functionality to write to the parcel NFT metadata
- Update the following UI elements to read name & link from the NFT metadata where appropriate
  - Parcel Details window
  - User dashboard/portfolio
  - Parcel lists (eg recent claims)

This project is part of the [Geo Web Core Roadmap](https://legacy.starmap.site/roadmap/github.com/Geo-Web-Project/docs/issues/18#detail).

Children:

ETA: 2023-10-27

Resources:

Note: This roadmap is subject to change as priorities and circumstances evolve.

### LINKED ISSUE #464: Separate the screens for editing parcel metadata & for sale prices
**Description**
Parcel name & link edits now require an onchain transaction (https://github.com/Geo-Web-Project/cadastre/issues/463). This function is separate from the one used to edit a parcel's `For Sale Price`, so combining these fields on a single entry form isn't practical. 

**Requirements**
- Remove the "Edit Parcel" button 
- Split the combined form into two ("Edit Metadata" & "Edit Price")
- Add two `Edit` icons for the two forms per the mocks below
  - Show an `Add Link` icon when a parcel doesn't have a link
- Move the functionality associated to the icons in the current parcel header into a new three-dot menu per the mocks
  - “Setup Notifications”
  - “Open Parcel in Spatial Browser”
  - “Copy a Sharable Link” 

Edit Parcel Metadata   For Sale Price

### LINKED ISSUE #466: Update Cadastre to new subgraph
Upon completion of https://github.com/Geo-Web-Project/geo-web-subgraph/issues/23,  update the Cadastre to use the new subgraph. This change should be used to fetch updates to parcel names for the profile modal parcel lists.

### LINKED ISSUE #467: Explore using different IPFS gateways for batched Cadastre calls
To improve availability while maintaining the ability to fetch batches of parcel-related IPFS data, we should explore moving off w3s.link which is blocked by many ISP (apparently). We need the ability batch the requests (like w3s offers) or another method to avoid hitting rate limits.

### PR DESCRIPTION
**Pull request by tnrdd**
# Description

Uses the Geo Web Parcel License NFT metadata to upload the parcel name and URL and read it back to show the info in the parcel panel.

# Issue

fixes #463, fixes #464, fixes #466, fixes #467

# Checklist:

- [x] My commit message follows the Conventional Commits specification
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my code
- [x] My changes generate no new warnings
- [x] My PR is rebased off the most recent `develop` branch
- [x] My PR is opened against the `develop` branch

# Alert Reviewers

@codynhat @gravenp

### CODE REVIEW

**Comment by codynhat** [comment]
Looks like the Fleek build is failing with `12:10:22 AM 11/08/2023: error hardhat@2.10.1: The engine "node" is incompatible with this module. Expected version "^14.0.0 || ^16.0.0 || ^18.0.0". Got "20.9.0"`

I could change the Fleek image to use Node 18 instead of 20? What version are you using @tnrdd?

**Comment by tnrdd** [comment]
Seems like a library depends on an old version of Hardhat which requires Node to be at most version 18.

I think changing the Fleek Image to Node 18 would work, locally I installed the packages successfully on 16 and 18 and got the same error on 20.

**Comment by gravenp** [comment]
Awaiting https://github.com/Geo-Web-Project/cadastre/issues/466 to merge this to testnet

**Review by gravenp — APPROVED** [review]
Thanks, @tnrdd! New metadata approach looks good, updates are shown across the Cadastre quickly, and ipfs.io gateway isn't getting blocked/rate-limited. 

@codynhat this can be merged into `develop`.

**Review by gravenp — APPROVED** [review]

**Pull request merged**
